---
# This is a sample database file for the DataMapper ORM
:development: &defaults
  :adapter: postgres
  :database: joe_dev
  :username: postgres
  :password: postgres
  :host: localhost

:test:
  <<: *defaults
  :database: fightinjoe_test

:production:
  <<: *defaults
  :database: fightinjoe_production